### ISSUE TITLE
Remote devcontainer connection fails after extension install

### ISSUE THREAD

**Issue by tobiaswi** [DataDog/datadog-for-vscode#7] opened 2023-08-15 07:35 UTC
# Issue
After installing the Datadog VS Code extension, connecting to a remote dev container fails.

# Symptoms
Functional VS Code remote setup.
Start VS Code without remote connection.
Install Datadog Extension.
Connect to dev container (attach or rebuild and attach, same behavior).
Initial remote connection is successful.
Remote Extension host starts enabling extensions.
Once Datadog Extension is installed/loaded: connections first hangs, then drops and tries to reconnect.
VS Codes asks for confirmation to reconnect which results in a loop of fail/reconnect.

# Reproduce
I was able to reproduce the issue using a non-insider VS Code and fresh install of Ubuntu 22.04.2 TLS.
I confirmed it's the Datadog extension after bisecting the extensions one by one. I was able to reproduce with just the Datadog extension installed (pull remote development extension pack)
This issue affects remote devcontainer only. Remote connections to WSL work without issue.

VS Code is installed on Windows, using a remote connection to WSL.
Docker is installed in WSL, running the devcontainer.
### VS Code
```
Version: 1.82.0-insider (user setup)
Commit: cb94a70e1f43b411586907165c80d7870f10e18
Date: (1 hr ago)
Electron: 25.4.0
ElectronBuildld: 22958381
Chromium: 114.0.5735.248
Node.js: 18.15.0
11.4.18327-electron.O
OS: Windows NTx64 10.02621
```
### Windows
```
Version 22H2 (0S Build 22621.2134)
```
### WSL
``` 
Linux MR-MCH7M57D3 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
### Docker
``` 
Docker version 24.0.5, build ced0996
```

**Comment by m-paternostro** [comment] 2023-08-15 15:06
Thank you for reporting the issue and for taking the time to investigate it.

I'll share our progress on this topic here.

**Comment by robertohuertasm** [comment] 2023-08-23 14:16
Hi @tobiaswi, I've been trying to replicate your issue but it's working for me. This is the environment that I have used to try to replicate your scenario:

```sh
> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22621  0

> docker -v
Docker version 24.0.5, build ced0996

> wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134

> code -v
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64
```

The main difference here is the usage of stable vscode vs insights, but you mentioned that you were able to replicate this also with the stable version.

For the rest of it, Docker, WSL version and even Ubuntu distro seems to be the same. Windows version is slightly different, though.

What kind of devcontainer are you using? I tested this with `Ubuntu:jammy`, not sure if that could trigger something.

Also, could you be so kind to share the output of `wsl --version` with us?

What I find curious enough is that I couldn't follow your reproduction steps. You mentioned you installed the Datadog extension before connecting to the dev container. I did that and it was installed in my wsl, then I had to do that again for my container. Did you have the same experience?

![image](https://github.com/DataDog/datadog-for-vscode/assets/696981/07bc479a-503c-41d5-bf64-bac6fde7fe97)

We would certainly need more feedback to try to understand what's going on. 

When you said: "Docker is installed in WSL, running the devcontainer." I understand you're using Docker Desktop and enabled the WSL 2 or do you have a different scenario?

![image](https://github.com/DataDog/datadog-for-vscode/assets/696981/4349ffbc-3de5-419f-8d3b-bbee82556f64)

Thanks for your help!

**Comment by robertohuertasm** [comment] 2023-08-23 14:17
Btw, are you using vscode profiles by any chance?

**Comment by robertohuertasm** [comment] 2023-08-23 14:24
Regarding the Dev Containers extension, are you by any chance using the pre-release version?

![image](https://github.com/DataDog/datadog-for-vscode/assets/696981/c71ae69d-70a7-42c1-80de-ca01b99aedc0)

**Comment by robertohuertasm** [comment] 2023-08-23 14:32
@tobiaswi can you verify that you don't have the same behaviour if you run the devcontainer directly from Windows? I mean, if you copy the project to a non WSL folder? Does it work?

**Comment by robertohuertasm** [comment] 2023-08-23 15:07
@tobiaswi, never mind. I think I managed to reproduce your issue. Can you confirm what you see in the installed extensions? Do you see something like that?

![image](https://github.com/DataDog/datadog-for-vscode/assets/696981/41c6086e-6f8b-4d4e-a497-571bf091c327)

What I did to reproduce the issue is to install the extension directly in VS Code without even being connected to WSL. I was suspicious that this could be the cause in the first place. I'll need to confirm that, but we may have some process depending on git which is holding the initialization.

**Comment by robertohuertasm** [comment] 2023-08-23 19:07
Just for our own information. The issue can be also reproduced by:
- installing the extension locally on Windows
- opening any folder in WSL
- wait for ~1'30'' 
- VS Code will disconnect from WSL

**Comment by robertohuertasm** [comment] 2023-08-23 19:23
@tobiaswi for now, the workaround will be:
- close any remote connection
- uninstall the Datadog extension
- open the remote connection
- install the Datadog extension either in WSL or the Dev Container
- that should do the trick

We will continue with the investigation of the issue and try to provide a solution asap.

**Comment by robertohuertasm** [comment] 2023-08-23 21:29
Ok, found the cause of the issue. Will prepare a fix for this asap. Hopefully, we'll have it working for the next release this week. The idea is to remove the bug and show a warning to the user to install the extension in the container or wsl if that's not the case when running in remote scenarios. 

Thank you @tobiaswi for reporting this issue. 🙌🏻

**Comment by robertohuertasm** [comment] 2023-08-30 10:10
Closing this one as this has been fixed in [v1.1.0](https://marketplace.visualstudio.com/items?itemName=Datadog.datadog-vscode)

**Closed** 2023-08-30 10:10 UTC
Labels: bug

**Comment by tobiaswi** [comment] 2023-09-05 17:30
Hi @robertohuertasm, sorry for the late response, I enjoyed two great weeks of PTO after creating the issue and really didn't expect such a quick response and solution! 👍 

I just tested the latest version and can confirm the issue is solved.
You asked more questions about my setup, and I'd be incredibly happy to provide a more detailed description. As this is related to a customer I consult, I'm going to follow up with you through appropriate contacts (CSM, dd slack).

**Comment by robertohuertasm** [comment] 2023-09-06 07:56
Hi @tobiaswi! Happy to hear that you enjoyed those two weeks! 🌴 That's always a good thing! We finally understood under which circumstances this behaviour would trigger so we don't need further information. That being said, happy to learn more about the specifics of that customer.
